In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("with some columns - output.csv")

In [3]:
import re

In [4]:
def process_address(address):
    if type(address)==str:
        addr = [x.strip() for x in address.split(',')][-1]
        if addr!='':
            pattern = r"(.*) ([A-Z]{2}) (\d{5}(?:-\d{4})?)$"
            match = re.search(pattern, addr.strip())
            if match:
                city, state, postal_code = match.groups()
                #print('city: ', city, 'state: ', state,'code: ', postal_code)
                return ([city, state, postal_code])
    return ['', '', '']

In [5]:
df['Address'] = df['Address'].str.rstrip(', ')

In [6]:
new_cols = df['Address'].apply(process_address).apply(pd.Series)

In [7]:
col_names = ['City', 'State', 'PostalCode']
new_cols.columns = col_names[:len(new_cols.columns)]
new_cols

,OrganizationName,Addr1,Addr2,City,State,PostalCode
0,University of Rochester Medical Center,601 Elmwood Ave,,Rochester,NY,14642
1,Houston Methodist Gastroenterology Associates,6550 Fannin St,Suite 1201 Smith Tower,Houston,TX,77030
2,BJC Medical Group Gstroenterology at Missouri ...,3009 N Ballas Rd,Suite 359-C,St Louis,MO,63131
3,Cleveland Clinic,9500 Euclid Ave,Desk A30,Cleveland,OH,44195
4,Cleveland Clinic,9500 Euclid Ave,Desk A30,Cleveland,OH,44195
...,...,...,...,...,...,...
454,Northwestern Medicine Digestive Health Center,259 E Erie St,Suite 1600,Chicago,IL,60611
455,UI Health,1009 South Wood Street,4th Floor,Chicago,IL,60612
456,GI Associates,411 Westwood Dr,,Wausau,WI,54401
457,UF Health,2000 SW Archer Rd,,Gainesville,FL,32608
458,The Gastroenterology Group of Northern New Jersey,140 Sylvan Ave,,Englewood Cliffs,NJ,07632

In [8]:
df1 = pd.concat([df, new_cols], axis=1)

In [9]:
df1.to_csv('new new location with some cols - output.csv')